/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.smart_health_prediction_doc;

public final class R {
    public static final class array {
        public static final int Spinneritems=0x7f060002;
        public static final int nav_drawer_icons=0x7f060001;
        public static final int nav_drawer_items=0x7f060000;
    }
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Customize dimensions originally defined in res/values/dimens.xml (such as
         screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
    
         */
        public static final int activity_horizontal_margin=0x7f040000;
        public static final int activity_vertical_margin=0x7f040001;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int back7=0x7f020001;
        public static final int dis=0x7f020002;
        public static final int doc=0x7f020003;
        public static final int docdet=0x7f020004;
        public static final int docdis=0x7f020005;
        public static final int docicon=0x7f020006;
        public static final int doclog=0x7f020007;
        public static final int docnot=0x7f020008;
        public static final int docpat=0x7f020009;
        public static final int drawlist=0x7f02000a;
        public static final int feed=0x7f02000b;
        public static final int ic_drawer=0x7f02000c;
        public static final int ic_launcher=0x7f02000d;
        public static final int list_itembg_normal=0x7f02000e;
        public static final int list_itembg_presses=0x7f02000f;
        public static final int list_selector=0x7f020010;
        public static final int logout=0x7f020011;
        public static final int mydeatils=0x7f020012;
        public static final int not=0x7f020013;
        public static final int pat=0x7f020014;
        public static final int paticon=0x7f020015;
        public static final int ww=0x7f020016;
    }
    public static final class id {
        public static final int RelativeLayout1=0x7f09000b;
        public static final int action_settings=0x7f090030;
        public static final int addtxt=0x7f09001a;
        public static final int cancelbtn=0x7f090021;
        public static final int disiid=0x7f090004;
        public static final int dislist=0x7f09002e;
        public static final int disname=0x7f090006;
        public static final int dissym=0x7f090008;
        public static final int distype=0x7f09000a;
        public static final int drawer_layout=0x7f090000;
        public static final int editbtn=0x7f09001f;
        public static final int frameid=0x7f090001;
        public static final int icon=0x7f09000c;
        public static final int iddata=0x7f090014;
        public static final int idtxt=0x7f090013;
        public static final int listView1=0x7f090002;
        public static final int login=0x7f090010;
        public static final int nametxt=0x7f090016;
        public static final int notdis=0x7f090025;
        public static final int notlist=0x7f090022;
        public static final int notpid=0x7f090023;
        public static final int notsym=0x7f090024;
        public static final int nottime=0x7f090027;
        public static final int nottype=0x7f090026;
        public static final int pass=0x7f09000f;
        public static final int patadd=0x7f09002c;
        public static final int patage=0x7f09002b;
        public static final int patcon=0x7f09002d;
        public static final int patgen=0x7f09002a;
        public static final int patid=0x7f090028;
        public static final int patlist=0x7f09002f;
        public static final int patname=0x7f090029;
        public static final int spectxt=0x7f090018;
        public static final int tableRow1=0x7f090003;
        public static final int tableRow2=0x7f090005;
        public static final int tableRow3=0x7f090007;
        public static final int tableRow4=0x7f090009;
        public static final int tableRow5=0x7f09001b;
        public static final int tableRow6=0x7f09001e;
        public static final int tableRow7=0x7f090020;
        public static final int tableRow8=0x7f090012;
        public static final int teltxt=0x7f09001d;
        public static final int textView1=0x7f090011;
        public static final int textView2=0x7f090015;
        public static final int textView6=0x7f090017;
        public static final int textView7=0x7f090019;
        public static final int textView8=0x7f09001c;
        public static final int title=0x7f09000d;
        public static final int userid=0x7f09000e;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int disease_items=0x7f030001;
        public static final int drawerlist_item=0x7f030002;
        public static final int login=0x7f030003;
        public static final int my_details=0x7f030004;
        public static final int notification=0x7f030005;
        public static final int notification_items=0x7f030006;
        public static final int patient_items=0x7f030007;
        public static final int view_disease=0x7f030008;
        public static final int view_patient=0x7f030009;
    }
    public static final class menu {
        public static final int main=0x7f080000;
    }
    public static final class string {
        public static final int action_settings=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int desc_list_item_icon=0x7f050005;
        public static final int drawer_close=0x7f050004;
        public static final int drawer_open=0x7f050003;
        public static final int hello_world=0x7f050002;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
    }
}
